apiVersion: v1
kind: Secret
metadata:
  name: realtime-meeting-secrets
  namespace: realtime-meeting
  annotations:
    kubernetes.io/service-account.name: default
stringData:
  TEAMS_APP_ID: "set-me"
  TEAMS_APP_PASSWORD: "set-me"
  ZOOM_SDK_KEY: "set-me"
  ZOOM_SDK_SECRET: "set-me"
