apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: realtime-meeting
resources:
  - namespace.yaml
  - config/configmap.yaml
  - config/secrets-placeholder.yaml
  - apps/teams-bot-deployment.yaml
  - apps/zoom-bot-deployment.yaml
  - apps/stream-processor-deployment.yaml
  - apps/ingress.yaml
