apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
resources:
  - ../../base
images:
  - name: 000000000000.dkr.ecr.us-east-1.amazonaws.com/teams-bot
    newTag: dev
  - name: 000000000000.dkr.ecr.us-east-1.amazonaws.com/zoom-bot
    newTag: dev
  - name: 000000000000.dkr.ecr.us-east-1.amazonaws.com/stream-processor
    newTag: dev
patchesStrategicMerge:
  - replicas-patch.yaml
