apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: realtime-meeting
  namespace: realtime-meeting
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - host: teams.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: teams-bot
                port:
                  number: 80
    - host: zoom.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zoom-bot
                port:
                  number: 3000
    - host: streams.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stream-processor
                port:
                  number: 8080
